from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas
from datetime import datetime
import io
from xml.sax.saxutils import escape


class PDFReportGenerator:

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_styles()

    def _setup_styles(self):
        """Setup custom styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=26,
            textColor=colors.HexColor('#2563eb'),
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))

        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#1e293b'),
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))

        self.styles.add(ParagraphStyle(
            name='SubSectionHeader',
            parent=self.styles['Heading3'],
            fontSize=13,
            textColor=colors.HexColor('#334155'),
            spaceAfter=8,
            spaceBefore=8,
            fontName='Helvetica-Bold'
        ))

        self.styles.add(ParagraphStyle(
            name='NormalSmall',
            parent=self.styles['Normal'],
            fontSize=9,
            leading=11
        ))

        self.styles.add(ParagraphStyle(
            name='RiskText',
            parent=self.styles['Normal'],
            fontSize=9,
            leading=12,
            leftIndent=10
        ))

    def generate_report(self, report_data: dict) -> bytes:
        """Generate PDF report from data"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=2*cm,
            bottomMargin=2*cm
        )

        elements = []

        elements.extend(self._create_title_page(report_data))
        elements.append(PageBreak())

        elements.extend(self._create_executive_summary(report_data))
        elements.append(PageBreak())

        elements.extend(self._create_technical_details(report_data))

        doc.build(elements, onFirstPage=self._add_first_page_footer, onLaterPages=self._add_footer)

        pdf_bytes = buffer.getvalue()
        buffer.close()

        return pdf_bytes

    def _create_title_page(self, report_data: dict) -> list:
        elements = []

        elements.append(Spacer(1, 1*inch))

        title = Paragraph("SECURITY SCAN REPORT", self.styles['CustomTitle'])
        elements.append(title)
        elements.append(Spacer(1, 0.2*inch))

        subtitle = Paragraph("FullMute Web Scanner", self.styles['Heading3'])
        elements.append(subtitle)
        elements.append(Spacer(1, 1.5*inch))

        info_text = f"""
        <b>Report Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br/>
        <b>Generated By:</b> {report_data.get('generated_by', 'Unknown')}<br/>
        <b>Group ID:</b> {report_data.get('group_id', 'N/A')}<br/>
        <b>Total Targets:</b> {report_data.get('total_targets', 0)}<br/>
        """

        info_para = Paragraph(info_text, self.styles['NormalSmall'])
        elements.append(info_para)
        elements.append(Spacer(1, 2*inch))

        return elements

    def _create_executive_summary(self, report_data: dict) -> list:
        elements = []

        header = Paragraph("EXECUTIVE SUMMARY", self.styles['SectionHeader'])
        elements.append(header)

        summary = report_data.get('summary', {})

        total_exploits = sum(len(d.get('exploits', [])) for d in report_data.get('domains', []))
        total_ssh_creds = sum(len(d.get('ssh_credentials', [])) for d in report_data.get('domains', []))

        stats_data = [
            ['Metric', 'Value', 'Risk Level'],
            ['Total Targets Scanned', str(summary.get('scanned', 0)), '✓'],
            ['Targets with Vulnerabilities', str(summary.get('with_vulnerabilities', 0)),
             '⚠ HIGH' if summary.get('with_vulnerabilities', 0) > 0 else '✓ LOW'],
            ['Targets with Sensitive Files', str(summary.get('with_sensitive_files', 0)),
             '⚠ MEDIUM' if summary.get('with_sensitive_files', 0) > 0 else '✓ LOW'],
            ['Targets with Default Credentials', str(summary.get('with_default_credentials', 0)),
             '⚠ CRITICAL' if summary.get('with_default_credentials', 0) > 0 else '✓ LOW'],
            ['Total Exploits Found', str(total_exploits),
             '⚠ CRITICAL' if total_exploits > 0 else '✓ LOW'],
            ['SSH Credentials Compromised', str(total_ssh_creds),
             '⚠ CRITICAL' if total_ssh_creds > 0 else '✓ LOW'],
        ]

        stats_table = Table(stats_data, colWidths=[2.8*inch, 1.5*inch, 1.7*inch])
        stats_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563eb')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8fafc')),
            ('FONTNAME', (2, 1), (2, -1), 'Helvetica-Bold'),
        ]))

        elements.append(stats_table)
        elements.append(Spacer(1, 0.5*inch))

        # Risk Assessment
        risk_header = Paragraph("RISK ASSESSMENT & RECOMMENDATIONS", self.styles['SubSectionHeader'])
        elements.append(risk_header)

        has_default_creds = summary.get('with_default_credentials', 0) > 0
        if has_default_creds:
            total_creds = summary.get('total_default_credentials', 0)
            elements.extend(self._create_risk_item(
                f"Default Credentials Detected ({total_creds} found)",
                "CRITICAL",
                "Default or weak credentials allow attackers to easily gain unauthorized access.",
                "Change all default passwords immediately. Implement strong password policy and MFA."
            ))

        has_ssh_creds = summary.get('with_ssh_credentials', 0) > 0
        if has_ssh_creds:
            total_ssh = summary.get('total_ssh_credentials', 0)
            elements.extend(self._create_risk_item(
                f"SSH Credentials Compromised ({total_ssh} found)",
                "CRITICAL",
                "Valid SSH username/password combinations were discovered.",
                "Change all compromised passwords. Disable password authentication, use SSH keys only."
            ))

        has_sensitive = summary.get('with_sensitive_files', 0) > 0
        if has_sensitive:
            elements.extend(self._create_risk_item(
                "Exposed Sensitive Files",
                "HIGH",
                "Sensitive files are publicly accessible.",
                "Remove or restrict access to all exposed sensitive files. Move files outside web root."
            ))

        return elements

    def _create_risk_item(self, title: str, severity: str, description: str, recommendations: str) -> list:
        elements = []

        title_html = f"<b>[{severity}]</b> <b>{title}</b>"
        elements.append(Paragraph(title_html, self.styles['NormalSmall']))

        elements.append(Paragraph(f"<i>{description}</i>", self.styles['RiskText']))
        elements.append(Spacer(1, 0.1*inch))

        elements.append(Paragraph("<b>Recommendations:</b>", self.styles['NormalSmall']))
        elements.append(Paragraph(recommendations.replace('\n', '<br/>'), self.styles['RiskText']))
        elements.append(Spacer(1, 0.3*inch))

        return elements

    def _create_technical_details(self, report_data: dict) -> list:
        elements = []

        header = Paragraph("TECHNICAL DETAILS", self.styles['SectionHeader'])
        elements.append(header)

        domains_data = [['Domain', 'Technologies', 'CVEs', 'Sensitive Files', 'Default Creds', 'Risk Status']]

        for domain_info in report_data.get('domains', []):
            domain = domain_info.get('domain', 'Unknown')
            techs = len(domain_info.get('technologies', []))
            cves = len(domain_info.get('cves', []))
            files = len(domain_info.get('sensitive_files', []))
            creds = len(domain_info.get('default_credentials', []))

            if cves > 5 or files > 3 or creds > 0:
                status = '⚠ CRITICAL'
            elif cves > 0 or files > 0:
                status = '⚠ ISSUES FOUND'
            else:
                status = '✓ CLEAN'

            domains_data.append([
                domain[:30] + '...' if len(domain) > 30 else domain,
                str(techs),
                str(cves),
                str(files),
                str(creds),
                status
            ])

        if len(domains_data) == 1:
            elements.append(Paragraph("<i>No technical data available. Ensure scans have been completed.</i>", self.styles['NormalSmall']))
            return elements

        domains_table = Table(
            domains_data,
            colWidths=[1.55*inch, 0.75*inch, 0.55*inch, 0.85*inch, 0.85*inch, 1.2*inch],
            repeatRows=1,
        )
        domains_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563eb')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ]))

        elements.append(domains_table)
        elements.append(Spacer(1, 0.3*inch))

        details_header = Paragraph("SITES AND CVE DETAILS", self.styles['SubSectionHeader'])
        elements.append(details_header)
        for domain_info in report_data.get('domains', []):
            domain = escape(str(domain_info.get('domain', 'Unknown')))
            elements.append(Paragraph(domain, self.styles['SubSectionHeader']))

            cves = domain_info.get('cves', [])
            if isinstance(cves, dict):
                cves = [
                    dict(cve, technology=technology)
                    for technology, items in cves.items()
                    for cve in (items if isinstance(items, list) else [])
                    if isinstance(cve, dict)
                ]
            if cves:
                cve_rows = [['CVE', 'Severity', 'CVSS', 'Technology', 'Description']]
                for cve in cves if isinstance(cves, list) else []:
                    if not isinstance(cve, dict):
                        continue
                    cvss = cve.get('cvss', {}) if isinstance(cve.get('cvss'), dict) else {}
                    cve_rows.append([
                        escape(str(cve.get('cve_id') or cve.get('id') or 'Unknown')),
                        escape(str(cve.get('severity') or cvss.get('severity') or 'N/A')),
                        escape(str(cve.get('cvss_score') or cvss.get('score') or 'N/A')),
                        escape(str(cve.get('tech_name') or cve.get('technology') or 'N/A')),
                        escape(str(cve.get('description') or ''))[:500],
                    ])
                cve_table = Table(
                    [[Paragraph(str(cell), self.styles['NormalSmall']) for cell in row] for row in cve_rows],
                    colWidths=[1.0*inch, 0.75*inch, 0.55*inch, 1.15*inch, 3.0*inch],
                    repeatRows=1,
                )
                cve_table.setStyle(TableStyle([
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#dc2626')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                ]))
                elements.append(cve_table)
            else:
                elements.append(Paragraph("No CVEs found.", self.styles['NormalSmall']))

            open_ports = domain_info.get('open_ports', [])
            if open_ports:
                elements.append(Paragraph("OPEN PORTS AND SERVICE VULNERABILITIES", self.styles['Normal']))
                port_rows = [['Port', 'Service / Version', 'CVEs', 'Exploits']]
                for port in open_ports:
                    if not isinstance(port, dict):
                        continue
                    service = port.get('service') or port.get('product') or 'unknown'
                    version = port.get('version') or 'N/A'
                    port_cves = port.get('cves', [])
                    cve_ids = []
                    for port_cve in port_cves if isinstance(port_cves, list) else []:
                        if isinstance(port_cve, dict):
                            cve_ids.append(str(port_cve.get('cve_id') or port_cve.get('id') or 'Unknown'))
                    port_exploits = port.get('exploits', [])
                    exploit_count = sum(
                        len(item.get('exploits', []))
                        for item in port_exploits
                        if isinstance(item, dict) and isinstance(item.get('exploits'), list)
                    )
                    port_rows.append([
                        escape(str(port.get('port', 'N/A'))),
                        escape(f"{service} {version}"),
                        escape(', '.join(cve_ids) or 'None'),
                        escape(str(exploit_count)),
                    ])
                ports_table = Table(
                    [[Paragraph(str(cell), self.styles['NormalSmall']) for cell in row] for row in port_rows],
                    colWidths=[0.55*inch, 2.2*inch, 3.0*inch, 0.7*inch],
                    repeatRows=1,
                )
                ports_table.setStyle(TableStyle([
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#7c3aed')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                ]))
                elements.append(ports_table)
            elements.append(Spacer(1, 0.15*inch))

        return elements

    def _add_first_page_footer(self, canvas_obj, doc):
        self._add_footer(canvas_obj, doc)

        canvas_obj.saveState()

        stamp_x = A4[0] - 4*cm
        stamp_y = 4*cm

        canvas_obj.setStrokeColor(colors.black)
        canvas_obj.setLineWidth(2)
        canvas_obj.circle(stamp_x, stamp_y, 1.2*cm)

        canvas_obj.setStrokeColor(colors.black)
        canvas_obj.setLineWidth(1)
        canvas_obj.circle(stamp_x, stamp_y, 1*cm)

        canvas_obj.setFont('Helvetica-Bold', 7)
        canvas_obj.setFillColor(colors.black)
        canvas_obj.drawCentredString(stamp_x, stamp_y + 0.3*cm, "OFFICIAL")
        canvas_obj.drawCentredString(stamp_x, stamp_y, "FullMute")
        canvas_obj.drawCentredString(stamp_x, stamp_y - 0.3*cm, "VERIFIED")

        canvas_obj.restoreState()

    def _add_footer(self, canvas_obj, doc):
        canvas_obj.saveState()

        canvas_obj.setStrokeColor(colors.black)
        canvas_obj.setLineWidth(1)
        canvas_obj.line(2*cm, 2.5*cm, A4[0] - 2*cm, 2.5*cm)

        canvas_obj.setFont('Helvetica', 8)
        canvas_obj.setFillColor(colors.black)

        page_num = canvas_obj.getPageNumber()
        footer_text = f"FullMute Security Scanner | Confidential Report | Page {page_num}"
        canvas_obj.drawCentredString(A4[0]/2, 1.8*cm, footer_text)

        canvas_obj.setFont('Helvetica-Bold', 10)
        canvas_obj.setFillColor(colors.black)
        canvas_obj.drawRightString(A4[0] - 2*cm, 1.8*cm, "FullMute")

        canvas_obj.setFont('Helvetica', 8)
        canvas_obj.setFillColor(colors.black)
        canvas_obj.drawString(2*cm, 1.8*cm, f"Generated: {datetime.now().strftime('%Y-%m-%d')}")

        canvas_obj.restoreState()


def generate_pdf_report(report_data: dict) -> bytes:
    generator = PDFReportGenerator()
    return generator.generate_report(report_data)
