from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas
from datetime import datetime
import io


class PDFReportGenerator:
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_styles()
    
    def _setup_styles(self):
        """Setup custom styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=26,
            textColor='
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor='
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='SubSectionHeader',
            parent=self.styles['Heading3'],
            fontSize=13,
            textColor='
            spaceAfter=8,
            spaceBefore=8,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='NormalSmall',
            parent=self.styles['Normal'],
            fontSize=9,
            leading=11
        ))
        
        self.styles.add(ParagraphStyle(
            name='RiskText',
            parent=self.styles['Normal'],
            fontSize=9,
            leading=12,
            leftIndent=10
        ))
    
    def generate_report(self, report_data: dict) -> bytes:
        """Generate PDF report from data"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=2*cm,
            bottomMargin=2*cm
        )
        
        elements = []
        
        
        elements.extend(self._create_title_page(report_data))
        elements.append(PageBreak())
        
        
        elements.extend(self._create_executive_summary(report_data))
        elements.append(PageBreak())
        
        
        elements.extend(self._create_technical_details(report_data))
        
        
        doc.build(elements, onFirstPage=self._add_first_page_footer, onLaterPages=self._add_footer)
        
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
    
    def _create_title_page(self, report_data: dict) -> list:
        elements = []
        
        
        elements.append(Spacer(1, 1*inch))
        
        
        title = Paragraph("SECURITY SCAN REPORT", self.styles['CustomTitle'])
        elements.append(title)
        elements.append(Spacer(1, 0.2*inch))
        
        
        subtitle = Paragraph("FullMute Web Scanner", self.styles['Heading3'])
        elements.append(subtitle)
        elements.append(Spacer(1, 1.5*inch))
        
        
        info_text = f"""
        <b>Report Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br/>
        <b>Generated By:</b> {report_data.get('generated_by', 'Unknown')}<br/>
        <b>Group ID:</b> {report_data.get('group_id', 'N/A')}<br/>
        <b>Total Targets:</b> {report_data.get('total_targets', 0)}<br/>
        """
        
        info_para = Paragraph(info_text, self.styles['NormalSmall'])
        elements.append(info_para)
        elements.append(Spacer(1, 2*inch))
        
        
        
        return elements
    
    def _create_executive_summary(self, report_data: dict) -> list:
        elements = []
        
        
        header = Paragraph("EXECUTIVE SUMMARY", self.styles['SectionHeader'])
        elements.append(header)
        
        
        summary = report_data.get('summary', {})

        
        total_exploits = sum(len(d.get('exploits', [])) for d in report_data.get('domains', []))
        total_ssh_creds = sum(len(d.get('ssh_credentials', [])) for d in report_data.get('domains', []))

        stats_data = [
            ['Metric', 'Value', 'Risk Level'],
            ['Total Targets Scanned', str(summary.get('scanned', 0)), '✓'],
            ['Targets with Vulnerabilities', str(summary.get('with_vulnerabilities', 0)),
             '⚠ HIGH' if summary.get('with_vulnerabilities', 0) > 0 else '✓ LOW'],
            ['Targets with Sensitive Files', str(summary.get('with_sensitive_files', 0)),
             '⚠ MEDIUM' if summary.get('with_sensitive_files', 0) > 0 else '✓ LOW'],
            ['Targets with Default Credentials', str(summary.get('with_default_credentials', 0)),
             '⚠ CRITICAL' if summary.get('with_default_credentials', 0) > 0 else '✓ LOW'],
            ['Total Exploits Found', str(total_exploits),
             '⚠ CRITICAL' if total_exploits > 0 else '✓ LOW'],
            ['SSH Credentials Compromised', str(total_ssh_creds),
             '⚠ CRITICAL' if total_ssh_creds > 0 else '✓ LOW'],
        ]
        
        stats_table = Table(stats_data, colWidths=[2.8*inch, 1.5*inch, 1.7*inch])
        stats_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, 'grey'),
            ('BACKGROUND', (0, 0), (-1, 0), '
            ('TEXTCOLOR', (0, 0), (-1, 0), 'white'),
            ('BACKGROUND', (0, 1), (-1, -1), '
            ('FONTNAME', (2, 1), (2, -1), 'Helvetica-Bold'),
        ]))
        
        elements.append(stats_table)
        elements.append(Spacer(1, 1*inch))
        
        
        risk_header = Paragraph("RISK ASSESSMENT & RECOMMENDATIONS", self.styles['SubSectionHeader'])
        elements.append(risk_header)

        
        has_default_creds = summary.get('with_default_credentials', 0) > 0
        if has_default_creds:
            total_creds = summary.get('total_default_credentials', 0)
            elements.extend(self._create_risk_item(
                f"Default Credentials Detected ({total_creds} found)",
                "CRITICAL",
                "Default or weak credentials allow attackers to easily gain unauthorized access to admin panels, CMS, databases, or other services. This is one of the most common attack vectors and can lead to complete system compromise.",
                "IMMEDIATE ACTIONS (within 24 hours):\n"
                "• Change ALL default passwords IMMEDIATELY on affected systems\n"
                "• Force password reset for all administrative accounts\n"
                "• Review access logs for suspicious login attempts\n"
                "• Enable account lockout after 3-5 failed attempts\n\n"
                "SHORT-TERM IMPROVEMENTS (within 1 week):\n"
                "• Implement strong password policy (min 12 chars, uppercase, lowercase, numbers, symbols)\n"
                "• Enable multi-factor authentication (MFA) on ALL admin accounts\n"
                "• Deploy a password manager for generating unique passwords\n"
                "• Implement single sign-on (SSO) if possible\n\n"
                "LONG-TERM SECURITY (ongoing):\n"
                "• Conduct quarterly password audits\n"
                "• Use automated tools to detect weak credentials\n"
                "• Implement privileged access management (PAM) solution\n"
                "• Train staff on password security best practices"
            ))

        
        has_ssh_creds = summary.get('with_ssh_credentials', 0) > 0
        if has_ssh_creds:
            total_ssh = summary.get('total_ssh_credentials', 0)
            elements.extend(self._create_risk_item(
                f"SSH Credentials Compromised ({total_ssh} found)",
                "CRITICAL",
                "Valid SSH username/password combinations were discovered. This allows attackers to gain remote shell access to your servers, potentially leading to complete system compromise, data theft, or lateral movement within your network.",
                "IMMEDIATE ACTIONS (within 24 hours):\n"
                "• Change ALL compromised SSH passwords IMMEDIATELY\n"
                "• Disable password authentication, use SSH keys only\n"
                "• Review /var/log/auth.log for unauthorized access\n"
                "• Block suspicious IP addresses in firewall\n\n"
                "SHORT-TERM IMPROVEMENTS (within 1 week):\n"
                "• Generate and deploy SSH key pairs for all users\n"
                "• Disable root login via SSH (PermitRootLogin no)\n"
                "• Change SSH port from default 22 to non-standard port\n"
                "• Install and configure fail2ban for brute-force protection\n\n"
                "LONG-TERM SECURITY (ongoing):\n"
                "• Implement centralized SSH key management\n"
                "• Use bastion hosts for SSH access\n"
                "• Enable SSH certificate authentication\n"
                "• Regular audit of SSH access logs"
            ))

        
        has_sensitive = summary.get('with_sensitive_files', 0) > 0
        if has_sensitive:
            elements.extend(self._create_risk_item(
                "Exposed Sensitive Files",
                "HIGH",
                "Sensitive files such as .git directories, .env files, configuration files, or database dumps are publicly accessible. This can lead to credential theft, source code exposure, database compromise, or server configuration disclosure.",
                "IMMEDIATE ACTIONS (within 24 hours):\n"
                "• Remove or restrict access to all exposed sensitive files\n"
                "• Rotate ANY credentials found in exposed files (.env, config.php, etc.)\n"
                "• Block access via web server configuration (.htaccess, nginx rules)\n"
                "• Review web server logs for unauthorized access\n\n"
                "SHORT-TERM IMPROVEMENTS (within 1 week):\n"
                "• Move sensitive files outside web root directory\n"
                "• Use environment variables instead of files for secrets\n"
                "• Implement proper file permissions (644 for files, 755 for directories)\n"
                "• Add security headers to prevent directory listing\n\n"
                "LONG-TERM SECURITY (ongoing):\n"
                "• Regularly audit file permissions and access controls\n"
                "• Implement automated scanning for exposed files\n"
                "• Use secrets management solutions (HashiCorp Vault, AWS Secrets Manager)\n"
                "• Conduct periodic security assessments"
            ))

        
        has_cves = summary.get('with_vulnerabilities', 0) > 0
        if has_cves:
            
            critical_count = 0
            high_count = 0
            medium_count = 0
            for domain in report_data.get('domains', []):
                for cve in domain.get('cves', []):
                    severity = cve.get('severity', '')
                    if severity == 'CRITICAL':
                        critical_count += 1
                    elif severity == 'HIGH':
                        high_count += 1
                    elif severity == 'MEDIUM':
                        medium_count += 1

            if critical_count > 0:
                elements.extend(self._create_risk_item(
                    f"Critical CVEs Detected ({critical_count} found)",
                    "CRITICAL",
                    "Critical vulnerabilities can allow remote code execution, complete system compromise, data breach, or service takeover. These require IMMEDIATE attention as they are actively exploited in the wild.",
                    "IMMEDIATE ACTIONS (within 24 hours):\n"
                    "• Apply security patches IMMEDIATELY - do not delay\n"
                    "• If patching is not possible, consider temporary service shutdown\n"
                    "• Implement WAF (Web Application Firewall) rules to block exploitation\n"
                    "• Enable enhanced logging and monitoring for attack signs\n"
                    "• Isolate affected systems from critical network segments\n\n"
                    "SHORT-TERM IMPROVEMENTS (within 1 week):\n"
                    "• Verify patch installation with vulnerability scanning\n"
                    "• Review and update incident response procedures\n"
                    "• Conduct threat hunting for signs of prior exploitation\n"
                    "• Update backup procedures and verify backup integrity\n\n"
                    "LONG-TERM SECURITY (ongoing):\n"
                    "• Implement automated patch management system\n"
                    "• Subscribe to vendor security advisories\n"
                    "• Establish vulnerability management program\n"
                    "• Conduct regular penetration testing"
                ))

            if high_count > 0:
                elements.extend(self._create_risk_item(
                    f"High Severity CVEs Detected ({high_count} found)",
                    "HIGH",
                    "High severity vulnerabilities can lead to significant data loss, privilege escalation, authentication bypass, or service disruption. These should be addressed promptly.",
                    "IMMEDIATE ACTIONS (within 72 hours):\n"
                    "• Schedule patching within 7 days maximum\n"
                    "• Review CVE details for specific remediation steps\n"
                    "• Implement network segmentation to limit exposure\n"
                    "• Enable logging and monitoring for affected services\n\n"
                    "SHORT-TERM IMPROVEMENTS (within 2 weeks):\n"
                    "• Test and deploy security patches\n"
                    "• Implement compensating controls if patching is delayed\n"
                    "• Review access controls and permissions\n"
                    "• Update firewall rules to restrict access\n\n"
                    "LONG-TERM SECURITY (ongoing):\n"
                    "• Establish patch management SLA (30 days for high severity)\n"
                    "• Implement automated vulnerability scanning\n"
                    "• Regular security awareness training\n"
                    "• Maintain asset inventory for quick impact assessment"
                ))

            if medium_count > 0:
                elements.extend(self._create_risk_item(
                    f"Medium Severity CVEs Detected ({medium_count} found)",
                    "MEDIUM",
                    "Medium severity vulnerabilities may lead to information disclosure, limited privilege escalation, or denial of service. These should be addressed in regular maintenance cycles.",
                    "RECOMMENDED ACTIONS (within 30 days):\n"
                    "• Include in next scheduled maintenance window\n"
                    "• Prioritize based on business impact and exploitability\n"
                    "• Monitor for new exploits or increased severity\n"
                    "• Document acceptance of risk if not immediately patched\n\n"
                    "LONG-TERM SECURITY (ongoing):\n"
                    "• Include in regular patch cycles\n"
                    "• Track and report on remediation progress\n"
                    "• Reassess priority if threat landscape changes"
                ))

        
        has_exploits = summary.get('with_exploits', 0) > 0
        if has_exploits:
            total_exploits = summary.get('total_exploits', 0)
            elements.extend(self._create_risk_item(
                f"Public Exploits Available ({total_exploits} found)",
                "CRITICAL",
                "Public exploits exist for your vulnerabilities. This means attackers can easily find and use ready-made exploit code to compromise your systems without advanced skills. These vulnerabilities are likely being actively exploited in the wild.",
                "IMMEDIATE ACTIONS (within 24 hours):\n"
                "• Apply security patches IMMEDIATELY - prioritize exploited CVEs\n"
                "• Deploy WAF rules to block known exploit patterns\n"
                "• Enable IPS/IDS signatures for these exploits\n"
                "• Monitor logs for exploitation attempts\n"
                "• Consider emergency maintenance window\n\n"
                "SHORT-TERM IMPROVEMENTS (within 1 week):\n"
                "• Verify patches are effective against exploits\n"
                "• Conduct threat hunting for compromise indicators\n"
                "• Review and harden affected services\n"
                "• Implement application whitelisting\n\n"
                "LONG-TERM SECURITY (ongoing):\n"
                "• Subscribe to exploit intelligence feeds (CISA KEV, etc.)\n"
                "• Prioritize patching based on exploit availability\n"
                "• Regular penetration testing with exploit simulation\n"
                "• Implement deception technology (honeypots)"
            ))

        
        if not has_default_creds and not has_sensitive and not has_cves:
            elements.extend(self._create_risk_item(
                "Excellent Security Posture",
                "LOW",
                "No significant security issues were detected during this scan. This indicates good security practices are in place.",
                "CONTINUE GOOD PRACTICES:\n"
                "• Maintain regular scanning schedule (weekly recommended)\n"
                "• Keep all software and dependencies up to date\n"
                "• Continue security awareness training\n"
                "• Monitor for new vulnerabilities and threats\n\n"
                "ADDITIONAL RECOMMENDATIONS:\n"
                "• Consider implementing automated security testing in CI/CD\n"
                "• Conduct periodic penetration testing\n"
                "• Review and update security policies annually\n"
                "• Implement security metrics and reporting"
            ))

        
        elements.extend(self._create_risk_item(
            "General Security Recommendations",
            "INFO",
            "Security is an ongoing process that requires continuous attention and improvement.",
            "AUTOMATION:\n"
            "• Implement weekly automated security scans\n"
            "• Set up alerting for critical findings\n"
            "• Integrate security scanning into CI/CD pipeline\n\n"
            "MONITORING:\n"
            "• Subscribe to vulnerability alerts for your technology stack\n"
            "• Implement SIEM or log analysis solution\n"
            "• Monitor for unusual access patterns\n\n"
            "GOVERNANCE:\n"
            "• Conduct periodic penetration testing (at least annually)\n"
            "• Train development team on secure coding practices (OWASP Top 10)\n"
            "• Implement a vulnerability management program\n"
            "• Maintain incident response procedures\n"
            "• Regular security policy reviews and updates"
        ))
        
        return elements
    
    def _create_risk_item(self, title: str, severity: str, description: str, recommendations: str) -> list:
        elements = []
        
        
        severity_color = 'black'
        
        
        title_html = f"<b>[{severity}]</b> <b>{title}</b>"
        elements.append(Paragraph(title_html, self.styles['NormalSmall']))
        
        
        elements.append(Paragraph(f"<i>{description}</i>", self.styles['RiskText']))
        elements.append(Spacer(1, 0.1*inch))
        
        
        elements.append(Paragraph("<b>Recommendations:</b>", self.styles['NormalSmall']))
        elements.append(Paragraph(recommendations.replace('\n', '<br/>'), self.styles['RiskText']))
        elements.append(Spacer(1, 0.3*inch))
        
        return elements
    
    def _create_technical_details(self, report_data: dict) -> list:
        elements = []
        
        
        header = Paragraph("TECHNICAL DETAILS", self.styles['SectionHeader'])
        elements.append(header)
        
        
        domains_data = [['Domain', 'Technologies', 'CVEs', 'Sensitive Files', 'Default Creds', 'Risk Status']]

        for domain_info in report_data.get('domains', []):
            domain = domain_info.get('domain', 'Unknown')
            techs = len(domain_info.get('technologies', []))
            cves = len(domain_info.get('cves', []))
            files = len(domain_info.get('sensitive_files', []))
            creds = len(domain_info.get('default_credentials', []))

            if cves > 5 or files > 3 or creds > 0:
                status = '⚠ CRITICAL'
            elif cves > 0 or files > 0:
                status = '⚠ ISSUES FOUND'
            else:
                status = '✓ CLEAN'

            domains_data.append([
                domain[:30] + '...' if len(domain) > 30 else domain,
                str(techs),
                str(cves),
                str(files),
                str(creds),
                status
            ])
        
        if len(domains_data) == 1:
            
            elements.append(Paragraph("<i>No technical data available. Ensure scans have been completed.</i>", self.styles['NormalSmall']))
            return elements
        
        domains_table = Table(domains_data, colWidths=[2.2*inch, 0.9*inch, 0.9*inch, 0.9*inch, 1.8*inch])
        domains_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, 'grey'),
            ('BACKGROUND', (0, 0), (-1, 0), '
            ('TEXTCOLOR', (0, 0), (-1, 0), 'white'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), ['
        ]))
        
        elements.append(domains_table)
        
        
        for domain_info in report_data.get('domains', []):
            elements.append(PageBreak())
            
            domain = domain_info.get('domain', 'Unknown')
            
            
            domain_header = Paragraph(f"Domain: {domain}", self.styles['SubSectionHeader'])
            elements.append(domain_header)
            
            
            if domain_info.get('technologies'):
                tech_header = Paragraph("Technologies Detected:", self.styles['Heading4'])
                elements.append(tech_header)
                
                tech_data = [['Name', 'Version', 'Category']]
                for tech in domain_info['technologies']:
                    tech_data.append([
                        tech.get('name', 'Unknown'),
                        tech.get('version', 'N/A'),
                        tech.get('category', 'Unknown')
                    ])
                
                tech_table = Table(tech_data, colWidths=[2*inch, 1.5*inch, 1.8*inch])
                tech_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('GRID', (0, 0), (-1, -1), 0.5, 'grey'),
                    ('BACKGROUND', (0, 0), (-1, 0), '
                    ('TEXTCOLOR', (0, 0), (-1, 0), 'white'),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), ['
                ]))
                
                elements.append(tech_table)
                elements.append(Spacer(1, 0.5*inch))
            
            
            if domain_info.get('cves'):
                cve_header = Paragraph("Vulnerabilities (CVEs):", self.styles['Heading4'])
                elements.append(cve_header)
                
                cve_data = [['CVE ID', 'Severity', 'CVSS', 'Description']]
                for cve in domain_info['cves']:
                    severity = cve.get('severity', 'N/A')
                    
                    severity_color = 'black'
                    
                    
                    description = cve.get('description', 'No description available')
                    if description and len(description) > 150:
                        description = description[:150] + '...'
                    
                    cve_data.append([
                        cve.get('cve_id', 'Unknown'),
                        Paragraph(f"<b>{severity}</b>",
                                 self.styles['NormalSmall']),
                        str(cve.get('cvss_score', 'N/A')),
                        Paragraph(f"{description}", self.styles['NormalSmall'])
                    ])
                
                cve_table = Table(cve_data, colWidths=[1.5*inch, 1*inch, 0.7*inch, 3.3*inch])
                cve_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 7),
                    ('GRID', (0, 0), (-1, -1), 0.5, 'grey'),
                    ('BACKGROUND', (0, 0), (-1, 0), '
                    ('TEXTCOLOR', (0, 0), (-1, 0), 'white'),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), ['
                ]))
                
                elements.append(cve_table)
                elements.append(Spacer(1, 0.5*inch))
            
            
            if domain_info.get('sensitive_files'):
                files_header = Paragraph("Sensitive Files Found:", self.styles['Heading4'])
                elements.append(files_header)

                files_data = [['File Path', 'Type', 'Verification']]
                for file in domain_info['sensitive_files']:
                    files_data.append([
                        file.get('file_path', 'Unknown')[:45],
                        file.get('file_type', 'Unknown'),
                        file.get('verification_result', 'N/A')
                    ])

                files_table = Table(files_data, colWidths=[3.2*inch, 1.2*inch, 1.5*inch])
                files_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 7),
                    ('GRID', (0, 0), (-1, -1), 0.5, 'grey'),
                    ('BACKGROUND', (0, 0), (-1, 0), '
                    ('TEXTCOLOR', (0, 0), (-1, 0), 'white'),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), ['
                ]))

                elements.append(files_table)
                elements.append(Spacer(1, 0.5*inch))

            
            if domain_info.get('default_credentials'):
                creds_header = Paragraph("⚠ DEFAULT CREDENTIALS FOUND:", self.styles['Heading4'])
                elements.append(creds_header)

                creds_data = [['Login URL', 'Username', 'Password', 'Risk']]
                for cred in domain_info['default_credentials']:
                    creds_data.append([
                        cred.get('login_url', 'Unknown')[:35],
                        cred.get('username', 'Unknown'),
                        cred.get('password', 'N/A'),
                        'CRITICAL'
                    ])

                creds_table = Table(creds_data, colWidths=[2.5*inch, 1.2*inch, 1.2*inch, 1*inch])
                creds_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 7),
                    ('GRID', (0, 0), (-1, -1), 0.5, 'grey'),
                    ('BACKGROUND', (0, 0), (-1, 0), '
                    ('TEXTCOLOR', (0, 0), (-1, 0), 'white'),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), ['
                ]))

                elements.append(creds_table)
                elements.append(Spacer(1, 0.5*inch))

            
            if domain_info.get('ssh_credentials'):
                ssh_creds_header = Paragraph("⚠ SSH CREDENTIALS COMPROMISED:", self.styles['Heading4'])
                elements.append(ssh_creds_header)

                ssh_creds_data = [['Port', 'Service', 'Username', 'Password', 'Risk']]
                for cred in domain_info['ssh_credentials']:
                    ssh_creds_data.append([
                        str(cred.get('port', '22')),
                        cred.get('service', 'ssh'),
                        cred.get('username', 'Unknown'),
                        cred.get('password', 'N/A'),
                        'CRITICAL'
                    ])

                ssh_creds_table = Table(ssh_creds_data, colWidths=[0.8*inch, 1*inch, 1.5*inch, 1.5*inch, 1*inch])
                ssh_creds_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 7),
                    ('GRID', (0, 0), (-1, -1), 0.5, 'grey'),
                    ('BACKGROUND', (0, 0), (-1, 0), '
                    ('TEXTCOLOR', (0, 0), (-1, 0), 'white'),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), ['
                ]))

                elements.append(ssh_creds_table)
                elements.append(Spacer(1, 0.5*inch))

            
            if domain_info.get('exploits'):
                exploits_header = Paragraph("⚠ EXPLOITS AVAILABLE:", self.styles['Heading4'])
                elements.append(exploits_header)

                exploits_data = [['CVE ID', 'Port', 'Service', 'Exploit Description', 'Risk']]
                for exploit in domain_info['exploits']:
                    exploits_data.append([
                        exploit.get('cve_id', 'N/A')[:15] if exploit.get('cve_id') else 'N/A',
                        str(exploit.get('port', 'N/A')),
                        exploit.get('service', 'N/A')[:15],
                        (exploit.get('description', 'No description')[:40] + '...') if exploit.get('description') else 'N/A',
                        'HIGH'
                    ])

                exploits_table = Table(exploits_data, colWidths=[1.2*inch, 0.8*inch, 1*inch, 2.5*inch, 0.8*inch])
                exploits_table.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 7),
                    ('GRID', (0, 0), (-1, -1), 0.5, 'grey'),
                    ('BACKGROUND', (0, 0), (-1, 0), '
                    ('TEXTCOLOR', (0, 0), (-1, 0), 'white'),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), ['
                ]))

                elements.append(exploits_table)
                elements.append(Spacer(1, 0.5*inch))

        return elements
    
    def _add_first_page_footer(self, canvas_obj, doc):
        self._add_footer(canvas_obj, doc)
        
        
        canvas_obj.saveState()
        
        
        stamp_x = A4[0] - 4*cm
        stamp_y = 4*cm
        
        
        canvas_obj.setStrokeColor('black')
        canvas_obj.setLineWidth(2)
        canvas_obj.circle(stamp_x, stamp_y, 1.2*cm)
        
        
        canvas_obj.setStrokeColor('black')
        canvas_obj.setLineWidth(1)
        canvas_obj.circle(stamp_x, stamp_y, 1*cm)
        
        
        canvas_obj.setFont('Helvetica-Bold', 7)
        canvas_obj.setFillColor('black')
        canvas_obj.drawCentredString(stamp_x, stamp_y + 0.3*cm, "OFFICIAL")
        canvas_obj.drawCentredString(stamp_x, stamp_y, "FullMute")
        canvas_obj.drawCentredString(stamp_x, stamp_y - 0.3*cm, "VERIFIED")
        
        canvas_obj.restoreState()
    
    def _add_footer(self, canvas_obj, doc):
        canvas_obj.saveState()
        
        
        canvas_obj.setStrokeColor('black')
        canvas_obj.setLineWidth(1)
        canvas_obj.line(2*cm, 2.5*cm, A4[0] - 2*cm, 2.5*cm)
        
        
        canvas_obj.setFont('Helvetica', 8)
        canvas_obj.setFillColor('black')
        
        
        page_num = canvas_obj.getPageNumber()
        footer_text = f"FullMute Security Scanner | Confidential Report | Page {page_num}"
        canvas_obj.drawCentredString(A4[0]/2, 1.8*cm, footer_text)
        
        
        canvas_obj.setFont('Helvetica-Bold', 10)
        canvas_obj.setFillColor('black')
        canvas_obj.drawRightString(A4[0] - 2*cm, 1.8*cm, "FullMute")
        
        
        canvas_obj.setFont('Helvetica', 8)
        canvas_obj.setFillColor('black')
        canvas_obj.drawString(2*cm, 1.8*cm, f"Generated: {datetime.now().strftime('%Y-%m-%d')}")
        
        canvas_obj.restoreState()


def generate_pdf_report(report_data: dict) -> bytes:
    generator = PDFReportGenerator()
    return generator.generate_report(report_data)
